import Vue from "vue";
import IconCart from "./IconCart";
import IconDashboard from "./IconDashboard";
import IconBarGraph from "./IconBarGraph";
import IconStore from "./IconStore";
import IconPlus from "./IconPlus";
import IconSave from "./IconSave";

Vue.component("icon-cart", IconCart);
Vue.component("icon-dashboard", IconDashboard);
Vue.component("icon-bar-graph", IconBarGraph);
Vue.component("icon-store", IconStore);
Vue.component("icon-plus", IconPlus);
Vue.component("icon-save", IconSave);
Vue.component("icon-puff", require("./icon-puff"));
Vue.component("icon-trash", require("./icon-trash"));
Vue.component("icon-search", require("./icon-search"));
Vue.component("icon-minus-square", require("./icon-minus-square"));
Vue.component("icon-print", require("./icon-print"));
Vue.component("icon-user", require("./icon-user"));
